# Plantilla: Libreria sin Docker
# Proyectos: shared, modulos comunes
#
# Instrucciones:
# 1. Copiar este archivo a .github/workflows/ci.yml en tu proyecto
# 2. Ajustar coverage-threshold (librerias suelen tener mayor cobertura)
# 3. Commit y push

name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    name: Run Tests
    uses: EduGoGroup/edugo-infrastructure/.github/workflows/reusable/go-test.yml@v1.0.0
    with:
      go-version: '1.25'
      coverage-threshold: 60  # Librerias suelen tener mayor cobertura
      run-race: true
      test-flags: '-short -v'
      upload-coverage: true
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Run Linter
    uses: EduGoGroup/edugo-infrastructure/.github/workflows/reusable/go-lint.yml@v1.0.0
    with:
      go-version: '1.25'
      golangci-lint-version: 'v1.64.7'
      args: '--timeout=5m'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
