# Plantilla: API con Docker
# Proyectos: api-mobile, api-admin, worker
#
# Instrucciones:
# 1. Copiar este archivo a .github/workflows/ci.yml en tu proyecto
# 2. Reemplazar {{IMAGE_NAME}} con el nombre de tu imagen (ej: api-mobile)
# 3. Ajustar coverage-threshold si necesario
# 4. Commit y push

name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    name: Run Tests
    uses: EduGoGroup/edugo-infrastructure/.github/workflows/reusable/go-test.yml@v1.0.0
    with:
      go-version: '1.25'
      coverage-threshold: 33  # Ajustar segun proyecto
      run-race: true
      test-flags: '-short'
      upload-coverage: true
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Run Linter
    uses: EduGoGroup/edugo-infrastructure/.github/workflows/reusable/go-lint.yml@v1.0.0
    with:
      go-version: '1.25'
      golangci-lint-version: 'v1.64.7'
      args: '--timeout=5m'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Build Docker Image
    needs: [test, lint]
    if: github.ref == 'refs/heads/main'
    uses: EduGoGroup/edugo-infrastructure/.github/workflows/reusable/docker-build.yml@v1.0.0
    with:
      image-name: '{{IMAGE_NAME}}'  # REEMPLAZAR: api-mobile, api-admin, worker
      registry: 'ghcr.io'
      platforms: 'linux/amd64,linux/arm64'
      push: true
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
