MODULE_NAME = github.com/EduGoGroup/edugo-infrastructure/tools/mock-generator
MODULE_PATH = tools/mock-generator
ROOT_DIR = ../..
BUILD_DIR = build
BINARY_NAME = mock-generator
BUILD_COMMAND = mkdir -p $(BUILD_DIR) && go build -o $(BUILD_DIR)/$(BINARY_NAME) ./cmd

include ../../make/go-module.mk
